### ISSUE TITLE
레이아웃 수정 및 세팅

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#14]
## Description

레이아웃 css 수정 및 [심사중] 표시 헤더에 추가하기

## Todo List

- [ ] 헤더 css 수정
- [ ] 푸터 css 수정
- [ ] 심사중 표시가 헤더에 추가 → 페이지에 따라 표시/미표시 적용

## 참고
![image](https://user-images.githubusercontent.com/94879006/234636483-779c5580-7563-439a-97f5-581ec64315ec.png)
심사중 표시는 데이터가 상세히 설명되는 페이지에서만 헤더에 추가된다.
스크롤 내리면 헤더와 함께 상단에 고정되어 따라 내려온다.
