### ISSUE TITLE
지도 컴포넌트 구현

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#15]
## Description

상호작용 가능한 지도 컴포넌트 만들기

## Todo List

- [ ] 카테고리별 장소 검색하기
- [ ] 카테고리 버튼 지도 바깥으로 빼기
- [ ] 카테고리별로 이미지 마커 적용
- [ ] 카테고리 마커 클릭하면 장소 개요 간단하게 표시
- [ ] 카테고리 마커 외에 해당 매물 주소는 별도의 마커로 표시
- [ ] 현 지도 고정상태로 키워드로 장소 검색하기

**Comment by 05Castle** [comment]
panoID가 없어서 로드뷰를 표시하지 못하는 문제 발견.
아파트 단지의 보안 정책에 따라 단지 내 로드뷰 촬영을 하지 못해서 발생한 문제 같다.
당장 떠오르는 대책은 3개.
1. panoID를 받아오는 거리를 늘린다(현재 50m).
2. panoID가 없으면 로드뷰 토글을 비활성화 한다.
3. panoID가 없으면 로드뷰 전환했을 때, <50m이내 로드뷰 이미지가 없습니다>라고 표시한다.

- [ ] UX/UI 팀에 의견을 구하고 기능 구현 가능한지 확인하기

**Comment by 05Castle** [comment]
중복 렌더링 해결한 방법
```
// lat는 위도, lng 는 경도

const Map = ({ lat, lng }) => {

  useEffect(() => {
    const mapContainer = document.getElementById('map'); // 지도를 표시할 div
    const mapOption = {
      center: new window.kakao.maps.LatLng(lat, lng), // 지도의 중심좌표
      level: 3, // 지도의 확대 레벨
    };
    const mapComp = new window.kakao.maps.Map(mapContainer, mapOption); // 지도를 생성
  }, [lat]);

  return (
    <MapWrapper>
      <div id="map" />;
    </MapWrapper>
  );
};
```

위의 코드는 좌표가 바뀔때마다 map 객체가 계속 렌더링되면서 문제가 발생했음.
그래서 아래와 같이 코드를 수정.

```
```
