### ISSUE TITLE
api 명세 작성

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#25]
## Description

api 명세 초안 작성하기

## Todo List

- [x] 어떤 data를 받을 것인가 정리
- [x] response data의 key 이름 정하기 (혼동되지 않도록)
- [x] 백엔드에서 sort해서 받아올 데이터 구분
- [x] 백엔드에 초안 전달

**Comment by 05Castle** [comment]
초안 작성하여 백엔드 팀에 전달하였으며,
보다 상세하게 api 명세 확정하면서 테스트용 목업 데이터를 구축할 예정
