### ISSUE TITLE
입지 페이지 마무리

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#33]
## Description

탬 메뉴의 입지 페이지 마무리하기

## Todo List

- [x] 지도 컴포넌트 기본 형태를 로드뷰 오버레이 상태로 바꾸기
- [x] 카테고리 필터 제거
- [x] 지도 객체 중복 렌더링 방지
- [x] 주변 시설 정보 받아오기
- [x] 주변 시설 정보 표(table) 형태로 표시
- [x] 네이버 부동산 링크 버튼

## 받아와야 하는 주변 시설 정보

반경 **1km 이내**에서 **가장 가까운 순서**대로,
- [x] 지하철 2ea
- [x] 영화관 1ea
- [x] 근린공원 1ea
- [x] 백화점 1ea
- [x] 대형마트 1ea
- [x] 초등학교/중학교/고등학교/대학교 각각 1ea
- [x] 부동산중개업소 5ea

1km 이내에 데이터 없을 경우, 표에 '-'로 표시할 것.

> _영화관, 근린공원, 백화점은 .keywordSearch() 메서드로,
그 외에는 .categorySearch() 메서드로 찾아야 함._
