### ISSUE TITLE
table 구현

### ISSUE THREAD

**Issue by sihyun10** [growing-devs/easy-to-real-estate-frontend#34]
## Description
react-table 라이브러리를 사용해, 재사용 가능한 table 구현하기.

## Todo List

- [ ] 재사용 가능한 common component 생성
- [ ] 오성님이 레이아웃 작업해주신 곳에 table 넣어보기
- [ ] header 부분 포함해서 테이블 전체 디자인 다시 수정하기

**Comment by sihyun10** [comment]
현재 '등기부 을구' 페이지 부분만 MOCK_DATA.json을 작성해 화면에 작업해두었다. 하지만, 아직 디자인 부분이 완벽하게 해두지 못해서, 그부분 추가적으로 해야하고 '등기부 갑구'페이지의 테이블도 MOCK_DATA로 화면에 작업해둘것이다.
