### ISSUE TITLE
레이아웃 수정 2차

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#42]
## Description

레이아웃 2차 수정

## Todo List

- [ ] 사이드바 사이즈 수정
- [ ] 사이드바 반응형 적용
- [ ] 사이드바 심사하기 메뉴에 하위 메뉴 추가
- [ ] 사이드바에 심사 단계 표시
- [ ] 타이틀 컨테이너 사이즈 수정
- [ ] 타이틀 컨테이너 버튼 변경
- [ ] 터이틀 컨테이너 path에 따라 구성 변경
- [ ] 매물 요약 섹션 사이즈 수정
- [ ] 매물 요약 섹션, 심사 내용 섹션 따로따로 스크롤 구현
- [ ] 스크롤 바 커스텀

**Comment by 05Castle** [comment]
width: 1440px이하부터 가로 스크롤 바가 생겨야 하는데 아직 미적용 상태.

- [ ] 가로 스크롤바 적용

**Comment by 05Castle** [comment]
심사하기 메인 컨텐츠 영역 우측 패딩값 조정

- [ ] 패딩 조정
