### ISSUE TITLE
홈 화면 만들기

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#5]
## Description

홈 화면 구성하기

## Todo List

- [x] 홈 컴포넌트(타이틀, 메뉴 버튼) 생성 
- [x] 홈 컴포넌트 css 작업
- [x] 홈 메뉴 버튼 각 라우트로 연결
- [x] 홈 화면 레이아웃 설정 (헤더 안 보이고, 푸터만 표시)
- [x] 아이콘 수정 (Material Design Icons 적용하기)
- [x]  변경된 디자인으로 전체적으로 css 수정

## 확인된 사항

1. 아이콘은 Material Design Icons를 사용할 예정.

## 추가 확인 사항

1. Material Design Icons 적용하니 피그마 와이어 프레임과 아이콘의 디테일 차이 발생. UI 팀 피드백 받기.
2. PC 가로 화면만 대응할 예정인지, 세로 화면 대응은 계획 없는지 확인하기.   
(요즘에는 듀얼 모니터 사용이 흔하고, 모니터를 세로로 두고 웹 서치 용으로 쓰는 경우도 많기 때문.  하지만 페르소나를 생각하면 세로 모니터 사용 가능성은 낮다고 볼 수도 있다.)
