### ISSUE TITLE
차트, 표 라이브러리 조사

### ISSUE THREAD

**Issue by 05Castle** [growing-devs/easy-to-real-estate-frontend#6]
## Description

차트와 표를 만들 라이브러리 조사 및 테스트하고 어느 라이브러리 사용할지 정하기.

## Todo List

- [x] 차트 라이브러리 후보 조사
- [x] 차트 라이브러리 후보들 테스트 → 확정
- [x] 표 라이브러리 후보 조사
- [x] 표 라이브러리 후보들 테스트 → 확정

## 기타 사항

조사한 라이브러리는 본 이슈에 코멘트로 남겨두기.
```
ex)
차트 라이브러리로 recahrts 라는 라이브러리를 테스트하고 있습니다.
```

**Comment by 05Castle** [comment]
리액트에서 많이 쓰이는 차트 라이브러리는 recharts 와 chartjs.
아래는 공식 문서.
https://recharts.org/en-US/
https://react-chartjs-2.js.org/

**Comment by 05Castle** [comment]
표 라이브러리로 react-table이 많이 사용되는 듯 하다.
npm-trends에 따르면 react-virtualized와 react-window 도 비슷하게 자주 사용되는 것 같은데,
이 두 라이브러리는 단순히 표나 그리드만을 위한 라이브러리가 아니라 다양한 기능을 내포하고 있는 것 같다.

만약, table이나 grid만 그릴 용도라면
사용성과 패키지 용량도 비교해 봐야 할 듯.

**Comment by gitjoyoung** [comment]
멘토님 추천 d3 로 작업 진행중

**Comment by 05Castle** [comment]
표 라이브러리는 react-table로 확정하여 작업 진행중
