### ISSUE TITLE
깃 푸쉬 테스트 환경설정

### ISSUE THREAD

**Issue by gitjoyoung** [growing-devs/easy-to-real-estate-frontend#8]
## Description

협업을 위한 깃 포크 및 환경설정 세팅
깃 포크하고 할일들 순서 정리하기

git clone https://github.com/자신의계정/포크한저장소.git

git remote add upstream https://github.com/원본저장소.git

## Todo List

- [x] 1. 메인브린치 포크
- [x] 2. 리모트 설정
- [x] 3. 작업후 푸쉬시 선행으로 깃 메인브린치에서 풀로 가져오기 
- [x] 4. 개인 레파지토리에 푸쉬
- [x] 5. 풀리퀘스트 요청 슬랙에 업데이트 내역 알리기

**Comment by gitjoyoung** [comment]
완료하였음
